config/routes.rb
Ardenreed2::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  root :to => "static_pages#home"

  resources :boxrequests

  resources :others

  resources :pants

  resources :suits

  resources :shirts

  resources :orders

  resources :customers

  resources :meas_finals
  resources :meas_initials 
  

  devise_for :users

end

app/models/ability.rb
class Ability
	include CanCan::Ability

	def initialize(user)
		if user
		can :manage, :all
		else
		can :access, :home
		end
	end
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/boxrequest.rb
class Boxrequest < ActiveRecord::Base
  attr_accessible :customer_id, :date_sent, :sent_from, :followed_up, :request_date, :requesttype, :shipping_number
  belongs_to :customer

  validates :customer, presence: true
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  attr_accessible :address, :email, :height, :name, :phonenumber, :weight, :meas_initial_attributes, :boxrequest_attributes, :meas_final_attributes
  has_one :meas_initial, dependent: :destroy
  #line below creates meas_initial so it will show in the new_customer view
  before_create :build_meas_initial
  before_create :build_meas_final
  has_one :meas_final, dependent: :destroy
  accepts_nested_attributes_for :meas_initial
  accepts_nested_attributes_for :meas_final
  has_many :orders
  has_many :boxrequests
  belongs_to :user

end
#http://stackoverflow.com/questions/3808782/rails-best-practice-how-to-create-dependent-has-one-relations

app/models/customization.rb
class Customization < ActiveRecord::Base
  attr_accessible :customization, :product_id
  belongs_to :product
end

app/models/meas_final.rb
class MeasFinal < ActiveRecord::Base
  attr_accessible :belt, :chest, :crotch, :customer_id, :hip, :jacket_length, :knee, :neck, :pants_length, :shoulder_width, :sleeve_length, :sleeve_width, :thigh, :waist, :wrist
  belongs_to :customer
  validates :customer, presence: true
  validates_uniqueness_of :customer_id
end

app/models/meas_initial.rb
class MeasInitial < ActiveRecord::Base
  attr_accessible :customer_id, :belt_i, :chest_i, :crotch_i, :hip_i, :jacket_length_i, :knee_i, :neck_i, :pants_length_i, :shoulder_width_i, :sleeve_length_i, :sleeve_width_i, :thigh_i, :waist_i, :wrist_i
  belongs_to :customer
  validates :customer, presence: true
  validates_uniqueness_of :customer_id
end

app/models/order.rb
class Order < ActiveRecord::Base
  attr_accessible :customer_id, :order_number, :order_date, :assigned_factory, :order_value, :order_cogs, :order_discount, :order_gross, :status, :expected_ship_date, :shipped_date, :shipping_number, :altered, :refunded, :called, :alt_ref_cost, :shirts_attributes, :suits_attributes, :pants_attributes, :others_attributes
  has_many :shirts
  has_many :suits
  has_many :pants
  has_many :others

  belongs_to :customer
  validates :customer, :presence => true
  accepts_nested_attributes_for :shirts, allow_destroy: true
  accepts_nested_attributes_for :suits, allow_destroy: true
  accepts_nested_attributes_for :pants, allow_destroy: true
  accepts_nested_attributes_for :others, allow_destroy: true
end

app/models/other.rb
class Other < ActiveRecord::Base
  attr_accessible :description, :other_name, :price, :quantity
  belongs_to :order
end

app/models/pant.rb
class Pant < ActiveRecord::Base
  attr_accessible :cuffs, :pant_name, :pleats, :price, :quantity
  belongs_to :order
end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :order_id, :product_name, :product_price, :customizations_attributes
  has_many :customizations
  accepts_nested_attributes_for :customizations, allow_destroy: true
  belongs_to :order
end

app/models/shirt.rb
class Shirt < ActiveRecord::Base
  attr_accessible :bottom, :collar, :contrast_area, :contrast_color, :cuffs, :fit, :monongram, :placket, :pocket, :price, :quantity, :shirt_name
  belongs_to :order
end

app/models/suit.rb
class Suit < ActiveRecord::Base
  attr_accessible :advanced, :button, :contrast_area, :contrast_color, :cuffs, :lapel, :pleats, :price, :quantity, :suit_name, :vent
  belongs_to :order
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  has_many :customers
  has_many :orders
  # attr_accessible :title, :body
end

app/controllers/suits_controller.rb
class SuitsController < ApplicationController
  # GET /suits
  # GET /suits.json
  def index
    @suits = Suit.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @suits }
    end
  end

  # GET /suits/1
  # GET /suits/1.json
  def show
    @suit = Suit.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @suit }
    end
  end

  # GET /suits/new
  # GET /suits/new.json
  def new
    @suit = Suit.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @suit }
    end
  end

  # GET /suits/1/edit
  def edit
    @suit = Suit.find(params[:id])
  end

  # POST /suits
  # POST /suits.json
  def create
    @suit = Suit.new(params[:suit])

    respond_to do |format|
      if @suit.save
        format.html { redirect_to @suit, notice: 'Suit was successfully created.' }
        format.json { render json: @suit, status: :created, location: @suit }
      else
        format.html { render action: "new" }
        format.json { render json: @suit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /suits/1
  # PUT /suits/1.json
  def update
    @suit = Suit.find(params[:id])

    respond_to do |format|
      if @suit.update_attributes(params[:suit])
        format.html { redirect_to @suit, notice: 'Suit was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @suit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /suits/1
  # DELETE /suits/1.json
  def destroy
    @suit = Suit.find(params[:id])
    @suit.destroy

    respond_to do |format|
      format.html { redirect_to suits_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	 def link_to_add_fields(name, f, association)
    new_object = f.object.send(association).klass.new
    id = new_object.object_id
    fields = f.fields_for(association, new_object, child_index: id) do |builder|
      render(association.to_s.singularize + "_fields", f: builder)
    end
    link_to(name, '#', class: "add_fields", data: {id: id, fields: fields.gsub("\n", "")})
  end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
	 def link_to_add_fields(name, f, association)
    new_object = f.object.send(association).klass.new
    id = new_object.object_id
    fields = f.fields_for(association, new_object, child_index: id) do |builder|
      render(association.to_s.singularize + "_fields", f: builder)
    end
    link_to(name, '#', class: "add_fields", data: {id: id, fields: fields.gsub("\n", "")})
  end
end

app/helpers/others_helper.rb
module OthersHelper
end

app/helpers/pants_helper.rb
module PantsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/shirts_helper.rb
module ShirtsHelper
end

app/helpers/suits_helper.rb
module SuitsHelper
end

app/views/suits/_form.html.erb
<%= simple_form_for(@suit) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :suit_name %>
    <%= f.input :price %>
    <%= f.input :lapel %>
    <%= f.input :vent %>
    <%= f.input :button %>
    <%= f.input :contrast_color %>
    <%= f.input :contrast_area %>
    <%= f.input :advanced %>
    <%= f.input :pleats %>
    <%= f.input :cuffs %>
    <%= f.input :quantity %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/suits/edit.html.erb
<h1>Editing suit</h1>

<%= render 'form' %>

<%= link_to 'Show', @suit %> |
<%= link_to 'Back', suits_path %>

app/views/suits/index.html.erb
<h1>Listing suits</h1>

<table>
  <tr>
    <th>Suit name</th>
    <th>Price</th>
    <th>Lapel</th>
    <th>Vent</th>
    <th>Button</th>
    <th>Contrast color</th>
    <th>Contrast area</th>
    <th>Advanced</th>
    <th>Pleats</th>
    <th>Cuffs</th>
    <th>Quantity</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @suits.each do |suit| %>
  <tr>
    <td><%= suit.suit_name %></td>
    <td><%= suit.price %></td>
    <td><%= suit.lapel %></td>
    <td><%= suit.vent %></td>
    <td><%= suit.button %></td>
    <td><%= suit.contrast_color %></td>
    <td><%= suit.contrast_area %></td>
    <td><%= suit.advanced %></td>
    <td><%= suit.pleats %></td>
    <td><%= suit.cuffs %></td>
    <td><%= suit.quantity %></td>
    <td><%= link_to 'Show', suit %></td>
    <td><%= link_to 'Edit', edit_suit_path(suit) %></td>
    <td><%= link_to 'Destroy', suit, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Suit', new_suit_path %>

app/views/suits/new.html.erb
<h1>New suit</h1>

<%= render 'form' %>

<%= link_to 'Back', suits_path %>

app/views/suits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Suit name:</b>
  <%= @suit.suit_name %>
</p>

<p>
  <b>Price:</b>
  <%= @suit.price %>
</p>

<p>
  <b>Lapel:</b>
  <%= @suit.lapel %>
</p>

<p>
  <b>Vent:</b>
  <%= @suit.vent %>
</p>

<p>
  <b>Button:</b>
  <%= @suit.button %>
</p>

<p>
  <b>Contrast color:</b>
  <%= @suit.contrast_color %>
</p>

<p>
  <b>Contrast area:</b>
  <%= @suit.contrast_area %>
</p>

<p>
  <b>Advanced:</b>
  <%= @suit.advanced %>
</p>

<p>
  <b>Pleats:</b>
  <%= @suit.pleats %>
</p>

<p>
  <b>Cuffs:</b>
  <%= @suit.cuffs %>
</p>

<p>
  <b>Quantity:</b>
  <%= @suit.quantity %>
</p>


<%= link_to 'Edit', edit_suit_path(@suit) %> |
<%= link_to 'Back', suits_path %>