config/routes.rb
Ardenreed2::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  root :to => "static_pages#home"

  resources :boxrequests

  resources :others

  resources :pants

  resources :suits

  resources :shirts

  resources :orders

  resources :customers

  resources :meas_finals
  resources :meas_initials 
  

  devise_for :users

end

app/models/ability.rb
class Ability
	include CanCan::Ability

	def initialize(user)
		if user
		can :manage, :all
		else
		can :access, :home
		end
	end
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/boxrequest.rb
class Boxrequest < ActiveRecord::Base
  attr_accessible :customer_id, :date_sent, :sent_from, :followed_up, :request_date, :requesttype, :shipping_number
  belongs_to :customer

  validates :customer, presence: true
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  attr_accessible :address, :email, :height, :name, :phonenumber, :weight, :meas_initial_attributes, :boxrequest_attributes, :meas_final_attributes
  has_one :meas_initial, dependent: :destroy
  #line below creates meas_initial so it will show in the new_customer view
  before_create :build_meas_initial
  before_create :build_meas_final
  has_one :meas_final, dependent: :destroy
  accepts_nested_attributes_for :meas_initial
  accepts_nested_attributes_for :meas_final
  has_many :orders
  has_many :boxrequests
  belongs_to :user

end
#http://stackoverflow.com/questions/3808782/rails-best-practice-how-to-create-dependent-has-one-relations

app/models/customization.rb
class Customization < ActiveRecord::Base
  attr_accessible :customization, :product_id
  belongs_to :product
end

app/models/meas_final.rb
class MeasFinal < ActiveRecord::Base
  attr_accessible :belt, :chest, :crotch, :customer_id, :hip, :jacket_length, :knee, :neck, :pants_length, :shoulder_width, :sleeve_length, :sleeve_width, :thigh, :waist, :wrist
  belongs_to :customer
  validates :customer, presence: true
  validates_uniqueness_of :customer_id
end

app/models/meas_initial.rb
class MeasInitial < ActiveRecord::Base
  attr_accessible :customer_id, :belt_i, :chest_i, :crotch_i, :hip_i, :jacket_length_i, :knee_i, :neck_i, :pants_length_i, :shoulder_width_i, :sleeve_length_i, :sleeve_width_i, :thigh_i, :waist_i, :wrist_i
  belongs_to :customer
  validates :customer, presence: true
  validates_uniqueness_of :customer_id
end

app/models/order.rb
class Order < ActiveRecord::Base
  attr_accessible :customer_id, :order_number, :order_date, :assigned_factory, :order_value, :order_cogs, :order_discount, :order_gross, :status, :expected_ship_date, :shipped_date, :shipping_number, :altered, :refunded, :called, :alt_ref_cost, :shirts_attributes, :suits_attributes, :pants_attributes, :others_attributes
  has_many :shirts
  has_many :suits
  has_many :pants
  has_many :others

  belongs_to :customer
  validates :customer, :presence => true
  accepts_nested_attributes_for :shirts, allow_destroy: true
  accepts_nested_attributes_for :suits, allow_destroy: true
  accepts_nested_attributes_for :pants, allow_destroy: true
  accepts_nested_attributes_for :others, allow_destroy: true
end

app/models/other.rb
class Other < ActiveRecord::Base
  attr_accessible :description, :other_name, :price, :quantity
  belongs_to :order
end

app/models/pant.rb
class Pant < ActiveRecord::Base
  attr_accessible :cuffs, :pant_name, :pleats, :price, :quantity
  belongs_to :order
end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :order_id, :product_name, :product_price, :customizations_attributes
  has_many :customizations
  accepts_nested_attributes_for :customizations, allow_destroy: true
  belongs_to :order
end

app/models/shirt.rb
class Shirt < ActiveRecord::Base
  attr_accessible :bottom, :collar, :contrast_area, :contrast_color, :cuffs, :fit, :monongram, :placket, :pocket, :price, :quantity, :shirt_name
  belongs_to :order
end

app/models/suit.rb
class Suit < ActiveRecord::Base
  attr_accessible :advanced, :button, :contrast_area, :contrast_color, :cuffs, :lapel, :pleats, :price, :quantity, :suit_name, :vent
  belongs_to :order
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  has_many :customers
  has_many :orders
  # attr_accessible :title, :body
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  load_and_authorize_resource

  # GET /customers
  # GET /customers.json
  def index
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @customers }
    end
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @customer }
    end
  end

  # GET /customers/new
  # GET /customers/new.json
  def new
    @customer = Customer.new
    @meas_initial = @customer_build_meas_initial
    @meas_final = @customer_build_meas_final
    @customer.save
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @customer }
    end
  end

  # GET /customers/1/edit
  def edit
    @customer = Customer.find(params[:id])
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(params[:customer])

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render json: @customer, status: :created, location: @customer }
      else
        format.html { render action: "new" }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /customers/1
  # PUT /customers/1.json
  def update
    @customer = Customer.find(params[:id])

    respond_to do |format|
      if @customer.update_attributes(params[:customer])
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer = Customer.find(params[:id])
    @customer.destroy

    respond_to do |format|
      format.html { redirect_to customers_url }
      format.json { head :no_content }
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
	 def link_to_add_fields(name, f, association)
    new_object = f.object.send(association).klass.new
    id = new_object.object_id
    fields = f.fields_for(association, new_object, child_index: id) do |builder|
      render(association.to_s.singularize + "_fields", f: builder)
    end
    link_to(name, '#', class: "add_fields", data: {id: id, fields: fields.gsub("\n", "")})
  end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
	 def link_to_add_fields(name, f, association)
    new_object = f.object.send(association).klass.new
    id = new_object.object_id
    fields = f.fields_for(association, new_object, child_index: id) do |builder|
      render(association.to_s.singularize + "_fields", f: builder)
    end
    link_to(name, '#', class: "add_fields", data: {id: id, fields: fields.gsub("\n", "")})
  end
end

app/helpers/others_helper.rb
module OthersHelper
end

app/helpers/pants_helper.rb
module PantsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/shirts_helper.rb
module ShirtsHelper
end

app/helpers/suits_helper.rb
module SuitsHelper
end

app/views/customers/_form.html.erb
<%= simple_form_for(@customer) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :email %>
    <%= f.input :height %>
    <%= f.input :weight %>
    <%= f.input :phonenumber %>
    <% if @customer.meas_final.neck.present? %>
      <%= f.fields_for :meas_final do |builder| %>
        <%= render 'meas_final_fields', f: builder %>
      <% end %>
    <% else %>
      <%= f.fields_for :meas_initial do |builder| %>
        <%= render 'meas_init_fields', f: builder %>
      <% end %>
    <% end %>
  
  </div>
  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/customers/_meas_final_fields.html.erb
<fieldset>    
    <%= f.input :neck %>
    <%= f.input :chest %>
    <%= f.input :waist %>
    <%= f.input :jacket_length %>
    <%= f.input :shoulder_width %>
    <%= f.input :sleeve_length %>
    <%= f.input :sleeve_width %>
    <%= f.input :wrist %>
    <%= f.input :hip %>
    <%= f.input :pants_length %>
    <%= f.input :belt %>
    <%= f.input :thigh %>
    <%= f.input :knee %>
    <%= f.input :crotch %>
</fieldset>

app/views/customers/_meas_init_fields.html.erb
<fieldset>
    <%= f.input :neck_i %>
    <%= f.input :chest_i %> 
    <%= f.input :waist_i %> 
    <%= f.input :jacket_length_i %> 
    <%= f.input :shoulder_width_i %>
    <%= f.input :sleeve_length_i %>
    <%= f.input :sleeve_width_i %>
    <%= f.input :wrist_i %>
    <%= f.input :hip_i %>
    <%= f.input :pants_length_i %>
    <%= f.input :belt_i %>
    <%= f.input :thigh_i %> 
    <%= f.input :knee_i %>
    <%= f.input :crotch_i %>
</fieldset>

app/views/customers/_show_meas_final.html.erb
<p>
<b>Neck:</b>
<%= @customer.meas_final.neck %>
</p>

<p>
<b>Chest:</b>
<%= @customer.meas_final.chest %>
</p>

<p>
<b>Waist:</b>
<%= @customer.meas_final.waist %>
</p>

<p>
<b>Jacket length:</b>
<%= @customer.meas_final.jacket_length %>
</p>

<p>
<b>Shoulder width:</b>
<%= @customer.meas_final.shoulder_width %>
</p>

<p>
<b>Sleeve length:</b>
<%= @customer.meas_final.sleeve_length %>
</p>

<p>
<b>Sleeve width:</b>
<%= @customer.meas_final.sleeve_width %>
</p>

<p>
<b>Wrist:</b>
<%= @customer.meas_final.wrist %>
</p>

<p>
<b>Hip:</b>
<%= @customer.meas_final.hip %>
</p>

<p>
<b>Pants length:</b>
<%= @customer.meas_final.pants_length %>
</p>

<p>
<b>Belt:</b>
<%= @customer.meas_final.belt %>
</p>

<p>
<b>Thigh:</b>
<%= @customer.meas_final.thigh %>
</p>

<p>
<b>Knee:</b>
<%= @customer.meas_final.knee %>
</p>

<p>
<b>Crotch:</b>
<%= @customer.meas_final.crotch %>
</p>

app/views/customers/_show_meas_initial.html.erb
<p>
<b>Neck i:</b>
<%= @customer.meas_initial.neck_i %>
</p>

<p>
<b>Chest i:</b>
<%= @customer.meas_initial.chest_i %>
</p>

<p>
<b>Waist i:</b>
<%= @customer.meas_initial.waist_i %>
</p>

<p>
<b>Jacket length i:</b>
<%= @customer.meas_initial.jacket_length_i %>
</p>

<p>
<b>Shoulder width i:</b>
<%= @customer.meas_initial.shoulder_width_i %>
</p>

<p>
<b>Sleeve length i:</b>
<%= @customer.meas_initial.sleeve_length_i %>
</p>

<p>
<b>Sleeve width i:</b>
<%= @customer.meas_initial.sleeve_width_i %>
</p>

<p>
<b>Wrist i:</b>
<%= @customer.meas_initial.wrist_i %>
</p>

<p>
<b>Hip i:</b>
<%= @customer.meas_initial.hip_i %>
</p>

<p>
<b>Pants length i:</b>
<%= @customer.meas_initial.pants_length_i %>
</p>

<p>
<b>Belt i:</b>
<%= @customer.meas_initial.belt_i %>
</p>

<p>
<b>Thigh i:</b>
<%= @customer.meas_initial.thigh_i %>
</p>

<p>
<b>Knee i:</b>
<%= @customer.meas_initial.knee_i %>
</p>

<p>
<b>Crotch i:</b>
<%= @customer.meas_initial.crotch_i %>
</p>

app/views/customers/edit.html.erb
<h1>Editing customer</h1>

<%= simple_form_for(@customer) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :email %>
    <%= f.input :height %>
    <%= f.input :weight %>
    <%= f.input :phonenumber %>
	  <%= f.fields_for :meas_initial do |builder| %>
	    <%= render 'meas_init_fields', f: builder %>
	  <% end %>
	 <%= f.fields_for :meas_final do |builder| %>
	    <%= render 'meas_final_fields', f: builder %>
	  <% end %>
  </div>
  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>



<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

app/views/customers/index.html.erb
<h1>Customers List</h1>

<table class="table">
  <tr>
    <th>ID</th>
    <th>Name</th>
    <th>Address</th>
    <th>Email</th>
    <th>Height</th>
    <th>Weight</th>
    <th>Phonenumber</th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @customers.each do |customer| %>
  <tr>
    <td><%= customer.id %></td>
    <td><%= customer.name %></td>
    <td><%= customer.address %></td>
    <td><%= customer.email %></td>
    <td><%= customer.height %></td>
    <td><%= customer.weight %></td>
    <td><%= customer.phonenumber %></td>
     

     <% if can? :update, @final_path %>   


    <%end%>

    <td><%= link_to 'Show', customer, class: "btn btn-mini" %></td>
    <% if can? :update, @customer %>
    <td><%= link_to 'Edit', edit_customer_path(customer), class: "btn btn-mini btn-primary" %></td>
    <%end%>
    <% if can? :destroy, @customer %>
    <td><%= link_to 'Destroy', customer, confirm: 'Are you sure?', method: :delete, class: "btn btn-mini btn-danger" %></td>
    <%end%>
    <td>
     <%= link_to 'New Order', new_order_path(:customer_id => customer.id), class: "btn btn-mini btn-primary" %></td>   
     <td>
     <%= link_to 'New Box', new_boxrequest_path(:customer_id => customer.id), class: "btn btn-mini btn-primary" %></td>   
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Customer', new_customer_path, class: "btn btn-mini btn-primary" %>

app/views/customers/new.html.erb
<h1>New customer</h1>

<%= simple_form_for(@customer) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :email %>
    <%= f.input :height %>
    <%= f.input :weight %>
    <%= f.input :phonenumber %>
  	<%= f.fields_for :meas_initial do |builder| %>
    	<%= render 'meas_init_fields', f: builder %>
  	<% end %>
  </div>
  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

<%= link_to 'Back', customers_path %>

app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @customer.name %>
</p>

<p>
  <b>Address:</b>
  <%= @customer.address %>
</p>

<p>
  <b>Email:</b>
  <%= @customer.email %>
</p>

<p>
  <b>Height:</b>
  <%= @customer.height %>
</p>

<p>
  <b>Weight:</b>
  <%= @customer.weight %>
</p>

<p>
  <b>Phonenumber:</b>
  <%= @customer.phonenumber %>
</p>

<% if @customer.meas_final.neck.present? %>
    <%= render 'show_meas_final' %>
<% else %>
     <%= render 'show_meas_initial' %>
  <% end %>


<%= link_to 'Edit', edit_customer_path(@customer) %> |
<%= link_to 'Back', customers_path %>