config/routes.rb
Ardenreed2::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  root :to => "static_pages#home"

  resources :boxrequests

  resources :others

  resources :pants

  resources :suits

  resources :shirts

  resources :orders

  resources :customers

  resources :meas_finals
  resources :meas_initials 
  

  devise_for :users

end

app/models/ability.rb
class Ability
	include CanCan::Ability

	def initialize(user)
		if user
		can :manage, :all
		else
		can :access, :home
		end
	end
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/boxrequest.rb
class Boxrequest < ActiveRecord::Base
  attr_accessible :customer_id, :date_sent, :sent_from, :followed_up, :request_date, :requesttype, :shipping_number
  belongs_to :customer

  validates :customer, presence: true
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  attr_accessible :address, :email, :height, :name, :phonenumber, :weight, :meas_initial_attributes, :boxrequest_attributes, :meas_final_attributes
  has_one :meas_initial, dependent: :destroy
  #line below creates meas_initial so it will show in the new_customer view
  before_create :build_meas_initial
  before_create :build_meas_final
  has_one :meas_final, dependent: :destroy
  accepts_nested_attributes_for :meas_initial
  accepts_nested_attributes_for :meas_final
  has_many :orders
  has_many :boxrequests
  belongs_to :user

end
#http://stackoverflow.com/questions/3808782/rails-best-practice-how-to-create-dependent-has-one-relations

app/models/customization.rb
class Customization < ActiveRecord::Base
  attr_accessible :customization, :product_id
  belongs_to :product
end

app/models/meas_final.rb
class MeasFinal < ActiveRecord::Base
  attr_accessible :belt, :chest, :crotch, :customer_id, :hip, :jacket_length, :knee, :neck, :pants_length, :shoulder_width, :sleeve_length, :sleeve_width, :thigh, :waist, :wrist
  belongs_to :customer
  validates :customer, presence: true
  validates_uniqueness_of :customer_id
end

app/models/meas_initial.rb
class MeasInitial < ActiveRecord::Base
  attr_accessible :customer_id, :belt_i, :chest_i, :crotch_i, :hip_i, :jacket_length_i, :knee_i, :neck_i, :pants_length_i, :shoulder_width_i, :sleeve_length_i, :sleeve_width_i, :thigh_i, :waist_i, :wrist_i
  belongs_to :customer
  validates :customer, presence: true
  validates_uniqueness_of :customer_id
end

app/models/order.rb
class Order < ActiveRecord::Base
  attr_accessible :customer_id, :order_number, :order_date, :assigned_factory, :order_value, :order_cogs, :order_discount, :order_gross, :status, :expected_ship_date, :shipped_date, :shipping_number, :altered, :refunded, :called, :alt_ref_cost, :shirts_attributes, :suits_attributes, :pants_attributes, :others_attributes
  has_many :shirts
  has_many :suits
  has_many :pants
  has_many :others

  belongs_to :customer
  validates :customer, :presence => true
  accepts_nested_attributes_for :shirts, allow_destroy: true
  accepts_nested_attributes_for :suits, allow_destroy: true
  accepts_nested_attributes_for :pants, allow_destroy: true
  accepts_nested_attributes_for :others, allow_destroy: true
end

app/models/other.rb
class Other < ActiveRecord::Base
  attr_accessible :description, :other_name, :price, :quantity
  belongs_to :order
end

app/models/pant.rb
class Pant < ActiveRecord::Base
  attr_accessible :cuffs, :pant_name, :pleats, :price, :quantity
  belongs_to :order
end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :order_id, :product_name, :product_price, :customizations_attributes
  has_many :customizations
  accepts_nested_attributes_for :customizations, allow_destroy: true
  belongs_to :order
end

app/models/shirt.rb
class Shirt < ActiveRecord::Base
  attr_accessible :bottom, :collar, :contrast_area, :contrast_color, :cuffs, :fit, :monongram, :placket, :pocket, :price, :quantity, :shirt_name
  belongs_to :order
end

app/models/suit.rb
class Suit < ActiveRecord::Base
  attr_accessible :advanced, :button, :contrast_area, :contrast_color, :cuffs, :lapel, :pleats, :price, :quantity, :suit_name, :vent
  belongs_to :order
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  has_many :customers
  has_many :orders
  # attr_accessible :title, :body
end

app/controllers/shirts_controller.rb
class ShirtsController < ApplicationController
  # GET /shirts
  # GET /shirts.json
  def index
    @shirts = Shirt.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @shirts }
    end
  end

  # GET /shirts/1
  # GET /shirts/1.json
  def show
    @shirt = Shirt.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @shirt }
    end
  end

  # GET /shirts/new
  # GET /shirts/new.json
  def new
    @shirt = Shirt.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @shirt }
    end
  end

  # GET /shirts/1/edit
  def edit
    @shirt = Shirt.find(params[:id])
  end

  # POST /shirts
  # POST /shirts.json
  def create
    @shirt = Shirt.new(params[:shirt])

    respond_to do |format|
      if @shirt.save
        format.html { redirect_to @shirt, notice: 'Shirt was successfully created.' }
        format.json { render json: @shirt, status: :created, location: @shirt }
      else
        format.html { render action: "new" }
        format.json { render json: @shirt.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /shirts/1
  # PUT /shirts/1.json
  def update
    @shirt = Shirt.find(params[:id])

    respond_to do |format|
      if @shirt.update_attributes(params[:shirt])
        format.html { redirect_to @shirt, notice: 'Shirt was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @shirt.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shirts/1
  # DELETE /shirts/1.json
  def destroy
    @shirt = Shirt.find(params[:id])
    @shirt.destroy

    respond_to do |format|
      format.html { redirect_to shirts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	 def link_to_add_fields(name, f, association)
    new_object = f.object.send(association).klass.new
    id = new_object.object_id
    fields = f.fields_for(association, new_object, child_index: id) do |builder|
      render(association.to_s.singularize + "_fields", f: builder)
    end
    link_to(name, '#', class: "add_fields", data: {id: id, fields: fields.gsub("\n", "")})
  end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
	 def link_to_add_fields(name, f, association)
    new_object = f.object.send(association).klass.new
    id = new_object.object_id
    fields = f.fields_for(association, new_object, child_index: id) do |builder|
      render(association.to_s.singularize + "_fields", f: builder)
    end
    link_to(name, '#', class: "add_fields", data: {id: id, fields: fields.gsub("\n", "")})
  end
end

app/helpers/others_helper.rb
module OthersHelper
end

app/helpers/pants_helper.rb
module PantsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/shirts_helper.rb
module ShirtsHelper
end

app/helpers/suits_helper.rb
module SuitsHelper
end

app/views/shirts/_form.html.erb
<%= simple_form_for(@shirt) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :shirt_name %>
    <%= f.input :price %>
    <%= f.input :collar %>
    <%= f.input :cuffs %>
    <%= f.input :placket %>
    <%= f.input :pocket %>
    <%= f.input :fit %>
    <%= f.input :bottom %>
    <%= f.input :contrast_color %>
    <%= f.input :contrast_area %>
    <%= f.input :monongram %>
    <%= f.input :quantity %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/shirts/edit.html.erb
<h1>Editing shirt</h1>

<%= render 'form' %>

<%= link_to 'Show', @shirt %> |
<%= link_to 'Back', shirts_path %>

app/views/shirts/index.html.erb
<h1>Listing shirts</h1>

<table>
  <tr>
    <th>Shirt name</th>
    <th>Price</th>
    <th>Collar</th>
    <th>Cuffs</th>
    <th>Placket</th>
    <th>Pocket</th>
    <th>Fit</th>
    <th>Bottom</th>
    <th>Contrast color</th>
    <th>Contrast area</th>
    <th>Monongram</th>
    <th>Quantity</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @shirts.each do |shirt| %>
  <tr>
    <td><%= shirt.shirt_name %></td>
    <td><%= shirt.price %></td>
    <td><%= shirt.collar %></td>
    <td><%= shirt.cuffs %></td>
    <td><%= shirt.placket %></td>
    <td><%= shirt.pocket %></td>
    <td><%= shirt.fit %></td>
    <td><%= shirt.bottom %></td>
    <td><%= shirt.contrast_color %></td>
    <td><%= shirt.contrast_area %></td>
    <td><%= shirt.monongram %></td>
    <td><%= shirt.quantity %></td>
    <td><%= link_to 'Show', shirt %></td>
    <td><%= link_to 'Edit', edit_shirt_path(shirt) %></td>
    <td><%= link_to 'Destroy', shirt, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Shirt', new_shirt_path %>

app/views/shirts/new.html.erb
<h1>New shirt</h1>

<%= render 'form' %>

<%= link_to 'Back', shirts_path %>

app/views/shirts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Shirt name:</b>
  <%= @shirt.shirt_name %>
</p>

<p>
  <b>Price:</b>
  <%= @shirt.price %>
</p>

<p>
  <b>Collar:</b>
  <%= @shirt.collar %>
</p>

<p>
  <b>Cuffs:</b>
  <%= @shirt.cuffs %>
</p>

<p>
  <b>Placket:</b>
  <%= @shirt.placket %>
</p>

<p>
  <b>Pocket:</b>
  <%= @shirt.pocket %>
</p>

<p>
  <b>Fit:</b>
  <%= @shirt.fit %>
</p>

<p>
  <b>Bottom:</b>
  <%= @shirt.bottom %>
</p>

<p>
  <b>Contrast color:</b>
  <%= @shirt.contrast_color %>
</p>

<p>
  <b>Contrast area:</b>
  <%= @shirt.contrast_area %>
</p>

<p>
  <b>Monongram:</b>
  <%= @shirt.monongram %>
</p>

<p>
  <b>Quantity:</b>
  <%= @shirt.quantity %>
</p>


<%= link_to 'Edit', edit_shirt_path(@shirt) %> |
<%= link_to 'Back', shirts_path %>