config/routes.rb
Ardenreed2::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  root :to => "static_pages#home"

  resources :boxrequests

  resources :others

  resources :pants

  resources :suits

  resources :shirts

  resources :orders

  resources :customers

  resources :meas_finals
  resources :meas_initials 
  

  devise_for :users

end

app/models/ability.rb
class Ability
	include CanCan::Ability

	def initialize(user)
		if user
		can :manage, :all
		else
		can :access, :home
		end
	end
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/boxrequest.rb
class Boxrequest < ActiveRecord::Base
  attr_accessible :customer_id, :date_sent, :sent_from, :followed_up, :request_date, :requesttype, :shipping_number
  belongs_to :customer

  validates :customer, presence: true
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  attr_accessible :address, :email, :height, :name, :phonenumber, :weight, :meas_initial_attributes, :boxrequest_attributes, :meas_final_attributes
  has_one :meas_initial, dependent: :destroy
  #line below creates meas_initial so it will show in the new_customer view
  before_create :build_meas_initial
  before_create :build_meas_final
  has_one :meas_final, dependent: :destroy
  accepts_nested_attributes_for :meas_initial
  accepts_nested_attributes_for :meas_final
  has_many :orders
  has_many :boxrequests
  belongs_to :user

end
#http://stackoverflow.com/questions/3808782/rails-best-practice-how-to-create-dependent-has-one-relations

app/models/customization.rb
class Customization < ActiveRecord::Base
  attr_accessible :customization, :product_id
  belongs_to :product
end

app/models/meas_final.rb
class MeasFinal < ActiveRecord::Base
  attr_accessible :belt, :chest, :crotch, :customer_id, :hip, :jacket_length, :knee, :neck, :pants_length, :shoulder_width, :sleeve_length, :sleeve_width, :thigh, :waist, :wrist
  belongs_to :customer
  validates :customer, presence: true
  validates_uniqueness_of :customer_id
end

app/models/meas_initial.rb
class MeasInitial < ActiveRecord::Base
  attr_accessible :customer_id, :belt_i, :chest_i, :crotch_i, :hip_i, :jacket_length_i, :knee_i, :neck_i, :pants_length_i, :shoulder_width_i, :sleeve_length_i, :sleeve_width_i, :thigh_i, :waist_i, :wrist_i
  belongs_to :customer
  validates :customer, presence: true
  validates_uniqueness_of :customer_id
end

app/models/order.rb
class Order < ActiveRecord::Base
  attr_accessible :customer_id, :order_number, :order_date, :assigned_factory, :order_value, :order_cogs, :order_discount, :order_gross, :status, :expected_ship_date, :shipped_date, :shipping_number, :altered, :refunded, :called, :alt_ref_cost, :shirts_attributes, :suits_attributes, :pants_attributes, :others_attributes
  has_many :shirts
  has_many :suits
  has_many :pants
  has_many :others

  belongs_to :customer
  validates :customer, :presence => true
  accepts_nested_attributes_for :shirts, allow_destroy: true
  accepts_nested_attributes_for :suits, allow_destroy: true
  accepts_nested_attributes_for :pants, allow_destroy: true
  accepts_nested_attributes_for :others, allow_destroy: true
end

app/models/other.rb
class Other < ActiveRecord::Base
  attr_accessible :description, :other_name, :price, :quantity
  belongs_to :order
end

app/models/pant.rb
class Pant < ActiveRecord::Base
  attr_accessible :cuffs, :pant_name, :pleats, :price, :quantity
  belongs_to :order
end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :order_id, :product_name, :product_price, :customizations_attributes
  has_many :customizations
  accepts_nested_attributes_for :customizations, allow_destroy: true
  belongs_to :order
end

app/models/shirt.rb
class Shirt < ActiveRecord::Base
  attr_accessible :bottom, :collar, :contrast_area, :contrast_color, :cuffs, :fit, :monongram, :placket, :pocket, :price, :quantity, :shirt_name
  belongs_to :order
end

app/models/suit.rb
class Suit < ActiveRecord::Base
  attr_accessible :advanced, :button, :contrast_area, :contrast_color, :cuffs, :lapel, :pleats, :price, :quantity, :suit_name, :vent
  belongs_to :order
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  has_many :customers
  has_many :orders
  # attr_accessible :title, :body
end

app/controllers/meas_initials_controller.rb
class MeasInitialsController < ApplicationController
  # GET /meas_initials
  # GET /meas_initials.json
  def index
    @meas_initials = MeasInitial.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @meas_initials }
    end
  end

  # GET /meas_initials/1
  # GET /meas_initials/1.json
  def show
    @meas_initial = MeasInitial.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @meas_initial }
    end
  end

  # GET /meas_initials/new
  # GET /meas_initials/new.json
  def new
    @meas_initial = MeasInitial.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @meas_initial }
    end
  end

  # GET /meas_initials/1/edit
  def edit
    @meas_initial = MeasInitial.find(params[:id])
  end

  # POST /meas_initials
  # POST /meas_initials.json
  def create
    @meas_initial = MeasInitial.new(params[:meas_initial])

    respond_to do |format|
      if @meas_initial.save
        format.html { redirect_to @meas_initial, notice: 'Meas initial was successfully created.' }
        format.json { render json: @meas_initial, status: :created, location: @meas_initial }
      else
        format.html { render action: "new" }
        format.json { render json: @meas_initial.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /meas_initials/1
  # PUT /meas_initials/1.json
  def update
    @meas_initial = MeasInitial.find(params[:id])

    respond_to do |format|
      if @meas_initial.update_attributes(params[:meas_initial])
        format.html { redirect_to @meas_initial, notice: 'Meas initial was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @meas_initial.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meas_initials/1
  # DELETE /meas_initials/1.json
  def destroy
    @meas_initial = MeasInitial.find(params[:id])
    @meas_initial.destroy

    respond_to do |format|
      format.html { redirect_to meas_initials_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/meas_initials_helper.rb
module MeasInitialsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
	 def link_to_add_fields(name, f, association)
    new_object = f.object.send(association).klass.new
    id = new_object.object_id
    fields = f.fields_for(association, new_object, child_index: id) do |builder|
      render(association.to_s.singularize + "_fields", f: builder)
    end
    link_to(name, '#', class: "add_fields", data: {id: id, fields: fields.gsub("\n", "")})
  end
end

app/helpers/others_helper.rb
module OthersHelper
end

app/helpers/pants_helper.rb
module PantsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/shirts_helper.rb
module ShirtsHelper
end

app/helpers/suits_helper.rb
module SuitsHelper
end

app/views/meas_initials/_form.html.erb
<%= simple_form_for(@meas_initial) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :customer_id %>
    <%= f.input :neck_i %>
    <%= f.input :chest_i %>
    <%= f.input :waist_i %>
    <%= f.input :jacket_length_i %>
    <%= f.input :shoulder_width_i %>
    <%= f.input :sleeve_length_i %>
    <%= f.input :sleeve_width_i %>
    <%= f.input :wrist_i %>
    <%= f.input :hip_i %>
    <%= f.input :pants_length_i %>
    <%= f.input :belt_i %>
    <%= f.input :thigh_i %>
    <%= f.input :knee_i %>
    <%= f.input :crotch_i %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/meas_initials/edit.html.erb
<h1>Editing meas_initial</h1>

<%= render 'form' %>

<%= link_to 'Show', @meas_initial %> |
<%= link_to 'Back', meas_initials_path %>

app/views/meas_initials/index.html.erb
<h1>Initial Measurements</h1>

<table class="table">
  <tr>
    <th>Customer</th>
    <th>Neck i</th>
    <th>Chest i</th>
    <th>Waist i</th>
    <th>Jacket length i</th>
    <th>Shoulder width i</th>
    <th>Sleeve length i</th>
    <th>Sleeve width i</th>
    <th>Wrist i</th>
    <th>Hip i</th>
    <th>Pants length i</th>
    <th>Belt i</th>
    <th>Thigh i</th>
    <th>Knee i</th>
    <th>Crotch i</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @meas_initials.each do |meas_initial| %>
  <tr>
    <td><%= meas_initial.customer_id %></td>
    <td><%= meas_initial.neck_i %></td>
    <td><%= meas_initial.chest_i %></td>
    <td><%= meas_initial.waist_i %></td>
    <td><%= meas_initial.jacket_length_i %></td>
    <td><%= meas_initial.shoulder_width_i %></td>
    <td><%= meas_initial.sleeve_length_i %></td>
    <td><%= meas_initial.sleeve_width_i %></td>
    <td><%= meas_initial.wrist_i %></td>
    <td><%= meas_initial.hip_i %></td>
    <td><%= meas_initial.pants_length_i %></td>
    <td><%= meas_initial.belt_i %></td>
    <td><%= meas_initial.thigh_i %></td>
    <td><%= meas_initial.knee_i %></td>
    <td><%= meas_initial.crotch_i %></td>
    <td><%= link_to 'Show', meas_initial, class: "btn btn-mini btn-primary" %></td>
    <td><%= link_to 'Edit', edit_meas_initial_path(meas_initial), class: "btn btn-mini" %></td>
    <td><%= link_to 'Destroy', meas_initial, confirm: 'Are you sure?', method: :delete, class: "btn btn-mini btn-danger" %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Meas initial', new_meas_initial_path %>

app/views/meas_initials/new.html.erb
<h1>New meas_initial</h1>

<%= render 'form' %>

<%= link_to 'Back', meas_initials_path %>

app/views/meas_initials/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Customer:</b>
  <%= @meas_initial.customer_id %>
</p>

<p>
  <b>Neck i:</b>
  <%= @meas_initial.neck_i %>
</p>

<p>
  <b>Chest i:</b>
  <%= @meas_initial.chest_i %>
</p>

<p>
  <b>Waist i:</b>
  <%= @meas_initial.waist_i %>
</p>

<p>
  <b>Jacket length i:</b>
  <%= @meas_initial.jacket_length_i %>
</p>

<p>
  <b>Shoulder width i:</b>
  <%= @meas_initial.shoulder_width_i %>
</p>

<p>
  <b>Sleeve length i:</b>
  <%= @meas_initial.sleeve_length_i %>
</p>

<p>
  <b>Sleeve width i:</b>
  <%= @meas_initial.sleeve_width_i %>
</p>

<p>
  <b>Wrist i:</b>
  <%= @meas_initial.wrist_i %>
</p>

<p>
  <b>Hip i:</b>
  <%= @meas_initial.hip_i %>
</p>

<p>
  <b>Pants length i:</b>
  <%= @meas_initial.pants_length_i %>
</p>

<p>
  <b>Belt i:</b>
  <%= @meas_initial.belt_i %>
</p>

<p>
  <b>Thigh i:</b>
  <%= @meas_initial.thigh_i %>
</p>

<p>
  <b>Knee i:</b>
  <%= @meas_initial.knee_i %>
</p>

<p>
  <b>Crotch i:</b>
  <%= @meas_initial.crotch_i %>
</p>


<%= link_to 'Edit', edit_meas_initial_path(@meas_initial) %> |
<%= link_to 'Back', meas_initials_path %>